CREATE TABLE `shop` (
  `ID` varchar(36) NOT NULL COMMENT '商店ID',
  `SHOP_NAME` varchar(50) DEFAULT NULL COMMENT '店铺名字',
  `SHOP_ADDRESS` varchar(100) DEFAULT NULL COMMENT '店铺地址',
  `SHOP_PATH` varchar(200) DEFAULT NULL COMMENT '店铺log',
  `SHOP_STATUS` int(1) DEFAULT 0 COMMENT '店铺状态 1为上线 0为下线',
  `SHOP_DESC` varchar(500) DEFAULT NULL COMMENT '店铺描述',
  `SHOP_PHONE` varchar(50) DEFAULT NULL COMMENT '店铺电话',
  `START_FEE` float(10,2) DEFAULT 0 COMMENT '起送费',
  `START_TIME` datetime DEFAULT NULL COMMENT '营业开始时间',
  `END_TIME` datetime DEFAULT NULL COMMENT '营业结束时间',
  `SHOP_ACTIVITY` varchar(500) DEFAULT NULL COMMENT '活动',
  `SHOP_HEAT` int DEFAULT 0 COMMENT '热度',
  `LONGITUDE` decimal(10,6) DEFAULT NULL COMMENT '经度',
  `LATITUDE` decimal(10,6) DEFAULT NULL COMMENT '纬度',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='店铺表';

CREATE TABLE `goods` (
  `ID` varchar(36) NOT NULL COMMENT '商品ID',
  `SHOP_ID` varchar(36) DEFAULT NULL COMMENT '店铺ID',
  `CLASS_ID` varchar(36) DEFAULT NULL COMMENT '类别ID',
  `GOODS_NAME` varchar(100) DEFAULT NULL COMMENT '商品名字',
  `GOODS_PRICE` float(10,2) DEFAULT 0 COMMENT '商品价格',
  `GOODS_STATUS` int(1) DEFAULT 1 COMMENT '商品状态 1为上架 0为下架 默认上架',
  `GOODS_DESC` varchar(500) DEFAULT NULL COMMENT '商品描述',
  `GOODS_HEAT` int DEFAULT 0 COMMENT '商品热度',
  `GOODS_PATH` varchar(200) DEFAULT NULL COMMENT '商品图片',
  `IS_DISCOUNT` int DEFAULT 0 COMMENT '是否打折 1为是 0为否 默认0',
  `GOODS_DISCOUNT` float(10,2) DEFAULT 1 COMMENT '折扣 默认为1 不打折',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='商品表';

CREATE TABLE `goodsclass` (
  `ID` varchar(36) NOT NULL COMMENT '菜单类别ID',
  `SHOP_ID` varchar(36) DEFAULT NULL COMMENT '店铺ID',
  `CLASS_NAME` varchar(50) DEFAULT NULL COMMENT '类型名称',
  `CLASS_STATUS` int(1) DEFAULT 1 COMMENT '类别状态 1为使用 0为不使用 默认1',
  `CLASS_NUM` int DEFAULT NULL COMMENT '类别顺序',
  `CLASS_DESC` varchar(500) DEFAULT NULL COMMENT '类别描述',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='菜单类别表';

CREATE TABLE `activity` (
  `ID` varchar(36) NOT NULL COMMENT '活动ID',
  `SHOP_ID` varchar(36) DEFAULT NULL COMMENT '店铺ID',
  `ACTIVITY_TYPE` int(1) DEFAULT 0 COMMENT '活动类型 0为平台活动 1位商铺活动',
  `ACTIVITY_TITLE` varchar(50) DEFAULT NULL COMMENT '活动标题',
  `ACTIVITY_STATUS` int(1) DEFAULT 0 COMMENT '活动状态 1为上线 0位下线',
  `START_TIME` datetime DEFAULT NULL COMMENT '开始时间',
  `END_TIME` datetime DEFAULT NULL COMMENT '结束时间',
  `ACTIVITY_DESC` varchar(500) DEFAULT NULL COMMENT '活动描述',
  `ACTIVITY_PATH` varchar(200) DEFAULT NULL COMMENT '活动图片',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='活动表';

CREATE TABLE `admin` (
  `ID` varchar(36) NOT NULL COMMENT '管理员ID',
  `ADMIN_NAME` varchar(50) DEFAULT NULL COMMENT '管理员名称',
  `ADMIN_PASSWORD` varchar(50) DEFAULT NULL COMMENT '管理员登录密码',
  `ADMIN_PHONE` varchar(50) DEFAULT NULL COMMENT '管理员电话',
  `ADMIN_STATUS` int(1) DEFAULT 1 COMMENT '管理员状态 0为禁用 1为正常',
  `ADMIN_DESC` varchar(500) DEFAULT NULL COMMENT '管理员描述',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='管理员表';

CREATE TABLE `user` (
  `ID` varchar(36) NOT NULL COMMENT '用户ID',
  `OPENID` varchar(36) DEFAULT NULL COMMENT '用户的唯一标识',
  `UNIONID` varchar(36) DEFAULT NULL COMMENT 'UnionID机制',
  `ADDRESS_ID` varchar(36) DEFAULT NULL COMMENT '地址ID//暂时不用',
  `USER_NAME` varchar(50) DEFAULT NULL COMMENT '用户名称',
  `USER_PHONE` varchar(50) DEFAULT NULL COMMENT '用户电话',
  `USER_ADDRESS` varchar(200) DEFAULT NULL COMMENT '用户地址',
  `USER_STATUS` int(1) DEFAULT 1 COMMENT '用户状态 0为禁用 1为正常',
  `USER_DESC` varchar(500) DEFAULT NULL COMMENT '用户描述',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户表';

CREATE TABLE `horseman` (
  `ID` varchar(36) NOT NULL COMMENT '骑手ID',
  `MAN_NAME` varchar(50) DEFAULT NULL COMMENT '骑手名字',
  `MAN_STATUS` int(1) DEFAULT 0 COMMENT '骑手状态 0为休息 1为工作',
  `MAN_PHONE` varchar(50) DEFAULT NULL COMMENT '骑手电话',
  `TAKEOUT_NUM` int DEFAULT 0 COMMENT '接单数量',
  `FINISH_NUM` int DEFAULT 0 COMMENT '完成订单数量',
  `MAN_TAKEMONEY` float(10,2) DEFAULT 0 COMMENT '接单金额',
  `MAN_FINISHMONEY` float(10,2) DEFAULT 0 COMMENT '完成订单金额',
  `MAN_DESC` datetime DEFAULT NULL COMMENT '骑手描述',
  `MAN_USER` varchar(36) NOT NULL COMMENT '登录用户名',
  `MAN_PASSWORD` varchar(36) NOT NULL COMMENT '登录密码',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='骑手表';

CREATE TABLE `order` (
  `ID` varchar(36) NOT NULL COMMENT '订单ID',
  `USER_ID` varchar(36) DEFAULT NULL COMMENT '用户ID',
  `MAN_ID` varchar(36) DEFAULT NULL COMMENT '骑手ID',
  `ADDRESS_ID` varchar(36) DEFAULT NULL COMMENT '地址ID',
  `ORDER_NAME` varchar(100) DEFAULT NULL COMMENT '订单TITLE',
  `PLACE_TIME` datetime DEFAULT NULL COMMENT '下单时间',
  `TAKING_TIME` datetime DEFAULT NULL COMMENT '接单时间',
  `FINISH_TIME` datetime DEFAULT NULL COMMENT '完成时间',
  `ORDER_TYPE` int(1) DEFAULT 0 COMMENT '订单类型 1为加急 0为一般',
  `ORDER_STATUS` int(1) DEFAULT 0 COMMENT '订单状态 0为 待接单 1为已接单，正在派送 2位已送达',
  `RECEIVER_INFO` varchar(50) DEFAULT NULL COMMENT '收货人信息',
  `RECEIVER_PHONE` varchar(50) DEFAULT NULL COMMENT '收货人电话',
  `ORDER_ADDRESS` varchar(200) DEFAULT NULL COMMENT '收货地址',
  `ORDER_TOTAL` float(10,2) DEFAULT 0 COMMENT '订单金额',
  `REAL_TOTAL` float(10,2) DEFAULT 0 COMMENT '实际金额',
  `PAY_WAY` int(1) DEFAULT 0 COMMENT '支付方式 0为微信 1为支付宝 2为货到付款',
  `ORDER_ISDISCOUNT` int(1) DEFAULT 0 COMMENT '是否打折 1为是 0为否',
  `ORDER_DISCOUNT` float(10,2) DEFAULT 0 COMMENT '折扣',
  `SEND_COST` float(10,2) DEFAULT 0 COMMENT '配送费',
  `BOX_COST` float(10,2) DEFAULT 0 COMMENT '餐盒费',
  `ORDER_DESC` varchar(500) DEFAULT NULL COMMENT '备注',
  `ORDER_TEXT` varchar(500) DEFAULT NULL COMMENT '订单说明',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='订单表';

CREATE TABLE `orderitem` (
  `ID` varchar(36) NOT NULL COMMENT '订单详情ID',
  `ORDER_ID` varchar(36) DEFAULT NULL COMMENT '订单ID',
  `GOODS_ID` varchar(36) DEFAULT NULL COMMENT '商品ID',
  `GOODS_NUM` int DEFAULT 0 COMMENT '商品数量',
  `GOODS_PRICE` float(10,2) DEFAULT 0 COMMENT '商品实际价格',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='订单详情表';


CREATE TABLE `address` (
  `ID` varchar(36) NOT NULL COMMENT '地址ID',
  `USER_ID` varchar(36) DEFAULT NULL COMMENT '用户ID',
  `ORDER_ID` varchar(36) DEFAULT NULL COMMENT '订单ID',
  `ADDRESS_PROVINCE` varchar(36) DEFAULT NULL COMMENT '省',
  `ADDRESS_CITY` varchar(36) DEFAULT NULL COMMENT '市',
  `ADDRESS_XIAN` varchar(36) DEFAULT NULL COMMENT '区/县',
  `ADDRESSS_TREET` varchar(36) DEFAULT NULL COMMENT '街道',
  `ADDRESSS_DETAIL` varchar(36) DEFAULT NULL COMMENT '详细',
  `LONGITUDE` varchar(36) DEFAULT NULL COMMENT '经度',
  `LATITUDE` varchar(36) DEFAULT NULL COMMENT '纬度',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='地址表';












